-- =====================================================================
-- Seed: /convocatoria para torneoid = 367
-- XXI TORNEO ANUAL DE GOLF — Club Las Lomas
-- Del 3 al 7 de noviembre de 2026
-- Fuente: 2026-CLL-CONVOCATORIA_ANUAL_torneo_367.pdf
-- Idempotente mediante ON DUPLICATE KEY UPDATE.
-- No modifica convocatorias de otros torneos ni administra privilegios.
-- =====================================================================

START TRANSACTION;

-- Sección 1: Descripción.
INSERT INTO convocatoria_content (torneoid, section_id, section_type, title, content, sort_order, enabled) VALUES
(367, 'descripcion', 'generic', 'Descripción', '{"text":"XXI TORNEO ANUAL DE GOLF — CLUB LAS LOMAS.\\nDel 3 al 7 de noviembre de 2026.\\n\\nCategorías para damas, caballeros y seniors. El torneo se jugará a 54 hoyos sin corte.\\n\\nPrimer turno por escopetazo a las 6:50 h y segundo turno a las 13:00 h. El martes 3 y el sábado 7 habrá escopetazo a las 8:30 h.\\n\\nCupo: categorías 1A a 5A limitadas en conjunto a 180 jugadores, distribuidos equitativamente por índice; categoría Senior limitada a 28 jugadores. La categoría definitiva se conocerá el 27 de octubre.\\n\\nInformes: 33 1086 1400 ext. 1555 · proshop@clublaslomas.com.mx."}', 1, 1)
ON DUPLICATE KEY UPDATE section_type=VALUES(section_type), title=VALUES(title), content=VALUES(content), sort_order=VALUES(sort_order), enabled=1, updated_at=CURRENT_TIMESTAMP;

-- Sección 2: Elegibilidad.
INSERT INTO convocatoria_content (torneoid, section_id, section_type, title, content, sort_order, enabled) VALUES
(367, 'elegibilidad', 'elegibilidad', 'Elegibilidad', '{"eligibilityText":"Podrán participar miembros de Club Las Lomas y golfistas amateurs mayores de 18 años. En Campeonato, AA y Damas también podrán participar jugadores mayores de 15 años. Es obligatorio acreditar el hándicap índex ante la Federación Mexicana de Golf; quienes no cuenten con registro FMG podrán demostrar su nivel mediante The Grint.","notesText":["La competencia se jugará con el hándicap índex del 1 de octubre de 2026 publicado en GHIN o GRINT. El Comité puede validar y ajustar el índex cuando sea necesario.","Se declarará desierta una categoría con menos de 8 participantes. La fecha límite para definirlo será el 23 de octubre de 2026; el Comité podrá fusionarla y ajustar rango de índex o formato.","Campeonato: índex 0 a 2.5, marcas azules, Stroke Play sin hándicap.","AA: índex 2.6 a 6.0, Stroke Play sin hándicap.","Categorías 1A a 3A: índex conjunto 6.1 a 34.3, marcas blancas, Stroke Play sin hándicap; se dividirán equitativamente cada 36 jugadores según índex.","Categorías 4A y 5A: índex conjunto 6.1 a 34.3, marcas blancas, Stableford sin hándicap; se dividirán equitativamente cada 36 jugadores según índex.","Senior 1 (60 años o más): índex 0 a 34.9 al 80%, marcas doradas, Stroke Play; trofeo 1 Gross y 1°, 2° y 3° Neto.","Damas 1: índex 0 a 25.1 al 80%, marcas rojas, Stroke Play; trofeo 1 Gross y 1°, 2° y 3° Neto.","Damas 2: índex 25.2 a 35.0 al 80%, marcas rojas, Stableford; trofeos por puntos al 1°, 2° y 3° lugar.","El uso de carrito de golf es obligatorio y puede compartirse con jugadores del mismo grupo. Cada jugador es responsable de contratar a su caddie al pagar la inscripción."],"inscripcionesText":"Fecha límite de inscripción: 31 de octubre de 2026 a las 16:00 h. No hay reembolsos. El Club Las Lomas se reserva el derecho de admisión. Informes: 33 1086 1400 ext. 1555 · proshop@clublaslomas.com.mx."}', 2, 1)
ON DUPLICATE KEY UPDATE section_type=VALUES(section_type), title=VALUES(title), content=VALUES(content), sort_order=VALUES(sort_order), enabled=1, updated_at=CURRENT_TIMESTAMP;

-- Sección 3: Costos.
INSERT INTO convocatoria_content (torneoid, section_id, section_type, title, content, sort_order, enabled) VALUES
(367, 'costos', 'generic', 'Costos', '{"sociosPricing":[{"title":"Membresía · 7 de abril al 31 de mayo","tiers":[{"categoria":"Caballeros y Senior","costo":"19500.00"},{"categoria":"Damas","costo":"17000.00"}]},{"title":"Membresía · 1 de junio al 31 de octubre","tiers":[{"categoria":"Caballeros y Senior","costo":"20500.00"},{"categoria":"Damas","costo":"18000.00"}]}],"foraneosPricing":[{"title":"Invitados · a partir del 1 de septiembre","caballeros":"21500.00","damasSeniors":"19000.00"}],"pricingNote":"Pago disponible a meses sin intereses. Más información directamente en Caja General.","contactInfo":{"bankName":"","clabe":"","cuenta":"","nombre":"","email":"proshop@clublaslomas.com.mx","telefono":"33 1086 1400 ext. 1555","telefonoDirecto":""},"contactWarning":"No hay reembolsos. El reemplazo deberá pertenecer a la misma categoría; si es invitado en sustitución de una membresía deberá pagar la diferencia.","inscripcionesText":"MEMBRESÍA INCLUYE: participación, eventos sociales, kit de bienvenida, carrito compartido en rondas de competencia, alimentos y bebidas en campo o área comercial, boleto individual no transferible para la cena concierto y un green fee vigente a noviembre de 2027.\\n\\nINVITADOS INCLUYE: dos rondas de práctica del 15 de septiembre al 23 de octubre de 2026, participación, eventos sociales, kit, carrito compartido, alimentos y bebidas, y boleto individual no transferible para la cena premiación."}', 3, 1)
ON DUPLICATE KEY UPDATE section_type=VALUES(section_type), title=VALUES(title), content=VALUES(content), sort_order=VALUES(sort_order), enabled=1, updated_at=CURRENT_TIMESTAMP;

-- Sección 4: Premiación.
INSERT INTO convocatoria_content (torneoid, section_id, section_type, title, content, sort_order, enabled) VALUES
(367, 'premiacion', 'list', 'Premiación', '{"items":[{"categoria":"Campeonato, AA, 1A, 2A y 3A — Stroke Play","premios":["Trofeo al 1er lugar.","Trofeo al 2do lugar.","Trofeo al 3er lugar."]},{"categoria":"4A y 5A — Stableford","premios":["Trofeo al 1er lugar por puntos.","Trofeo al 2do lugar por puntos.","Trofeo al 3er lugar por puntos."]},{"categoria":"Senior 1 y Damas 1","premios":["Trofeo al 1er lugar Gross.","Trofeos al 1°, 2° y 3° lugar Neto."]},{"categoria":"Damas 2 — Stableford","premios":["Trofeos al 1°, 2° y 3° lugar por puntos."]}]}', 4, 1)
ON DUPLICATE KEY UPDATE section_type=VALUES(section_type), title=VALUES(title), content=VALUES(content), sort_order=VALUES(sort_order), enabled=1, updated_at=CURRENT_TIMESTAMP;

-- Sección 5: Desempates.
INSERT INTO convocatoria_content (torneoid, section_id, section_type, title, content, sort_order, enabled) VALUES
(367, 'desempates', 'desempates', 'Desempates', '{"intro":"Criterios oficiales para formatos Stroke Play y Stableford.","showCorte":false,"showTrofeos":true,"paraCorte":[],"paraTrofeos":["El primer lugar de Campeonato se definirá por muerte súbita en los hoyos asignados por el Comité.","Para las demás posiciones, el desempate será por comparación de tarjetas: mejor score de los últimos 9 hoyos (10 al 18), luego últimos 6 (13 al 18), últimos 3 (16 al 18) y hoyo 18.","Si persiste el empate, se repetirá el procedimiento con los hoyos 1 al 9.","En categorías con hándicap se aplicarán las ventajas en los hoyos correspondientes. Los últimos 9 hoyos siempre se consideran del 10 al 18, aunque el jugador haya iniciado por el hoyo 10."],"nota":"Las decisiones del Comité y del juez designado serán finales e inapelables."}', 5, 1)
ON DUPLICATE KEY UPDATE section_type=VALUES(section_type), title=VALUES(title), content=VALUES(content), sort_order=VALUES(sort_order), enabled=1, updated_at=CURRENT_TIMESTAMP;

-- Sección 6: Competencias.
INSERT INTO convocatoria_content (torneoid, section_id, section_type, title, content, sort_order, enabled) VALUES
(367, 'competencias', 'list', 'Competencias', '{"items":[{"nombre":"HOLE IN ONE — hoyos 2, 12 y 17","descripcion":"Se premiará únicamente el primer Hole in One. Un segundo Hole in One se considerará como mejor O''Yes, siempre que corresponda a los días aplicables para la categoría. El ganador cubrirá las retenciones fiscales y esperará los trámites de la aseguradora.","premios":"Premio al primer Hole in One del torneo."},{"nombre":"O''YESES — hoyos 2, 6, 12 y 17","descripcion":"Participan todos los golfistas inscritos. Solo se entrega un premio por jugador; si marca más de un O''Yes recibe el de mayor valor, después el de menor distancia y finalmente el primero realizado.","premios":"1° $70,000.00 · 2° $50,000.00 · 3° $40,000.00 · 4° $30,000.00 · 5° $20,000.00."},{"nombre":"PUTT DEL MEDIO MILLÓN — miércoles 4","descripcion":"Competencia en el tee de práctica a las 18:00 h.","premios":"1°, 2° y 3° lugar."},{"nombre":"TORNEO DE PUTT — jueves 5","descripcion":"Competencia en el tee de práctica a las 18:00 h.","premios":"1° 3 green fees · 2° 2 green fees · 3° Putter TaylorMade."},{"nombre":"SHOOT OUT — viernes 6","descripcion":"Competencia en el tee de práctica a las 18:45 h.","premios":"1° 3 green fees · 2° 2 green fees · 3° Putter TaylorMade."}]}', 6, 1)
ON DUPLICATE KEY UPDATE section_type=VALUES(section_type), title=VALUES(title), content=VALUES(content), sort_order=VALUES(sort_order), enabled=1, updated_at=CURRENT_TIMESTAMP;

-- Sección 7: Programa.
INSERT INTO convocatoria_content (torneoid, section_id, section_type, title, content, sort_order, enabled) VALUES
(367, 'servicios', 'servicios', 'Programa', '{"items":[{"dia":"Martes 3 de noviembre","servicios":["Primera ronda · escopetazo 08:30 h","Cóctel y entrega de kits de bienvenida · alberca recreativa 19:00 h","Música DJ"]},{"dia":"Miércoles 4 de noviembre","servicios":["Rondas 06:50 y 13:00 h","Putt del medio millón · tee de práctica 18:00 h","Noche de magia y mentalismo"]},{"dia":"Jueves 5 de noviembre","servicios":["Rondas 06:50 y 13:00 h","Torneo de Putt · tee de práctica 18:00 h","Noche karaoke y DJ"]},{"dia":"Viernes 6 de noviembre","servicios":["Rondas 06:50 y 13:00 h","Shoot Out · tee de práctica 18:45 h","Banda de rock y Neón"]},{"dia":"Sábado 7 de noviembre","servicios":["Ronda final · escopetazo 08:30 h","Ceremonia de premiación, rifas y concierto MATUTE · explanada de golf 19:00 h","Cena concierto: invitado de jugador $6,800.00; incluye cena y bebidas de la casa"]},{"dia":"Todos los días","servicios":["Área comercial y lounge desde las 12:30 h con comida, música y bebidas en cortesía"]}]}', 7, 1)
ON DUPLICATE KEY UPDATE section_type=VALUES(section_type), title=VALUES(title), content=VALUES(content), sort_order=VALUES(sort_order), enabled=1, updated_at=CURRENT_TIMESTAMP;

-- Sección 8: Reglas Locales.
INSERT INTO convocatoria_content (torneoid, section_id, section_type, title, content, sort_order, enabled) VALUES
(367, 'reglas', 'reglas', 'Reglas Locales', '{"items":[{"titulo":"Reglas aplicables","contenido":"Se jugará bajo las Reglas de la USGA, las reglas locales y la presente convocatoria. Un juez designado por el Comité atenderá cualquier situación y sus decisiones serán inapelables."},{"titulo":"Código de vestimenta","contenido":"Se aplicará el código de vestimenta y los protocolos de etiqueta de Club Las Lomas indicados en las bases del torneo y condiciones de competencia."},{"titulo":"Carritos de golf","contenido":"El uso de carrito es obligatorio para todos los jugadores. Podrá utilizarse y compartirse por jugadores del mismo grupo."},{"titulo":"Caddies","contenido":"Cada jugador debe contratar a su propio caddie al pagar la inscripción. Si contrata uno externo deberá notificarlo al Proshop y cumplir el reglamento interno."},{"titulo":"Descalificación","contenido":"El jugador descalificado por cualquier razón perderá el derecho a recibir premios y no podrá continuar jugando el torneo."},{"titulo":"Horarios de salida","contenido":"Se publicarán dos días antes de cada jornada. Es responsabilidad del jugador verificar y confirmar su horario antes de cada ronda en Proshop, Motor Lobby o la página de SPEI Tour."},{"titulo":"Facultades del Comité","contenido":"El Comité Organizador se reserva el derecho de hacer los cambios que considere necesarios para el mejor desarrollo del torneo. Participar implica aceptar el fallo inapelable del Comité de Reglas."}]}', 8, 1)
ON DUPLICATE KEY UPDATE section_type=VALUES(section_type), title=VALUES(title), content=VALUES(content), sort_order=VALUES(sort_order), enabled=1, updated_at=CURRENT_TIMESTAMP;

COMMIT;
