-- =====================================================================
-- Seed: /convocatoria content for torneoid=349 (V Torneo Anual Terralta 2026)
-- Reglas locales y desempates viven en /reglas (ver seed reglas_torneo349_terralta).
-- Idempotente vía ON DUPLICATE KEY UPDATE.
-- =====================================================================

START TRANSACTION;

INSERT INTO convocatoria_content (torneoid, section_id, section_type, content, enabled) VALUES (349, 'descripcion', 'generic', '{"text": "Terralta A.C. celebra su V Torneo Anual de Invitación, edición 2026, del 26 de junio al 4 de julio de 2026 en las instalaciones del club.\\n\\nLa inscripción al Torneo Anual incluye: kit de bienvenida; Torneo de Putt Damas y Caballeros; Torneo de Approach Mixto; Torneo de Driver de Precisión Damas; Torneo de Driver de Distancia Caballeros; Torneo de Long Driver Caballeros; premios de O´yes; y alimentos y bebidas en los centros de consumo (jugador y cónyuge).\\n\\nPremio Hole In One: $1,000,000 al primer Hole In One en cualquiera de los 5 hoyos par 3. Si durante el torneo no se realiza ningún Hole In One, el premio se rifará entre los jugadores que hayan pagado su cuota de inscripción (la rifa se realiza el 4 de julio durante la Ceremonia de Premiación; es indispensable estar presente). Para un segundo o más Hole In One, el socio ganador recibirá un año de cuotas de mantenimiento sin costo; los no socios recibirán una membresía anual con cuota de mantenimiento incluida.\\n\\nDurante el desarrollo del Torneo queda restringido el acceso a menores de edad a la Casa Club, eventos sociales y premiación. Solo se autoriza el acceso a menores que jueguen en la categoría Premier de Caballeros y 1ª Categoría de Damas."}', 1)
ON DUPLICATE KEY UPDATE
  section_type = 'generic',
  content = '{"text": "Terralta A.C. celebra su V Torneo Anual de Invitación, edición 2026, del 26 de junio al 4 de julio de 2026 en las instalaciones del club.\\n\\nLa inscripción al Torneo Anual incluye: kit de bienvenida; Torneo de Putt Damas y Caballeros; Torneo de Approach Mixto; Torneo de Driver de Precisión Damas; Torneo de Driver de Distancia Caballeros; Torneo de Long Driver Caballeros; premios de O´yes; y alimentos y bebidas en los centros de consumo (jugador y cónyuge).\\n\\nPremio Hole In One: $1,000,000 al primer Hole In One en cualquiera de los 5 hoyos par 3. Si durante el torneo no se realiza ningún Hole In One, el premio se rifará entre los jugadores que hayan pagado su cuota de inscripción (la rifa se realiza el 4 de julio durante la Ceremonia de Premiación; es indispensable estar presente). Para un segundo o más Hole In One, el socio ganador recibirá un año de cuotas de mantenimiento sin costo; los no socios recibirán una membresía anual con cuota de mantenimiento incluida.\\n\\nDurante el desarrollo del Torneo queda restringido el acceso a menores de edad a la Casa Club, eventos sociales y premiación. Solo se autoriza el acceso a menores que jueguen en la categoría Premier de Caballeros y 1ª Categoría de Damas."}',
  enabled = 1,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO convocatoria_content (torneoid, section_id, section_type, content, enabled) VALUES (349, 'elegibilidad', 'generic', '{"eligibilityText": "Podrán participar damas y caballeros mayores de 18 años con estatus amateur que cuenten con hándicap GHIN vigente registrado en la FMG, publicado al 15 de mayo de 2026 (el más bajo si pertenecen a dos o más clubes).", "notesText": ["Categorías Campeonato y Premier (Caballeros): se permite participar a jugadores de 14 años en adelante con 0.0 de H.I., y deberán tener registros en torneos juveniles con scores por debajo de 85 golpes.", "Categorías Seniors: 50 a 60 años cumplidos al 15 de mayo de 2026. Super Seniors: 61 años o más cumplidos al 15 de mayo de 2026.", "1ª Categoría de Damas: se permite participar a jugadoras de 14 años en adelante con +5.0 a 14.8 de H.I., con registros en torneos juveniles con scores por debajo de 84 golpes.", "El Comité Organizador se reserva el derecho de aceptar a cualquier jugador o sembrarlo en otra categoría. Un jugador sin GHIN deberá firmar carta aceptando cualquier reclamación de otros jugadores y solo podrá participar por los premios de habilidades, O´yes, Hole In One y rifas, renunciando a la competencia principal.", "Hándicap: se jugará con el hándicap federado del 15 de mayo de 2026.", "Inscripciones para Socios: a partir del 16 de abril de 2026. Invitados: a partir del 1 de mayo de 2026. Cierre de inscripciones: 22 de junio de 2026.", "Brazalete: será indispensable el registro diario en la recepción del Club para contar con el brazalete de acceso al servicio de alimentos y bebidas. Debe portarse en la muñeca sin excepción."], "inscripcionesText": "Inscripciones: https://terralta.speitour.com (información del torneo, salidas, programa de juego y resultados).\\nInicio Socios: 16 de abril de 2026. Inicio Invitados: 1 de mayo de 2026. Cierre: 22 de junio de 2026."}', 1)
ON DUPLICATE KEY UPDATE
  section_type = 'generic',
  content = '{"eligibilityText": "Podrán participar damas y caballeros mayores de 18 años con estatus amateur que cuenten con hándicap GHIN vigente registrado en la FMG, publicado al 15 de mayo de 2026 (el más bajo si pertenecen a dos o más clubes).", "notesText": ["Categorías Campeonato y Premier (Caballeros): se permite participar a jugadores de 14 años en adelante con 0.0 de H.I., y deberán tener registros en torneos juveniles con scores por debajo de 85 golpes.", "Categorías Seniors: 50 a 60 años cumplidos al 15 de mayo de 2026. Super Seniors: 61 años o más cumplidos al 15 de mayo de 2026.", "1ª Categoría de Damas: se permite participar a jugadoras de 14 años en adelante con +5.0 a 14.8 de H.I., con registros en torneos juveniles con scores por debajo de 84 golpes.", "El Comité Organizador se reserva el derecho de aceptar a cualquier jugador o sembrarlo en otra categoría. Un jugador sin GHIN deberá firmar carta aceptando cualquier reclamación de otros jugadores y solo podrá participar por los premios de habilidades, O´yes, Hole In One y rifas, renunciando a la competencia principal.", "Hándicap: se jugará con el hándicap federado del 15 de mayo de 2026.", "Inscripciones para Socios: a partir del 16 de abril de 2026. Invitados: a partir del 1 de mayo de 2026. Cierre de inscripciones: 22 de junio de 2026.", "Brazalete: será indispensable el registro diario en la recepción del Club para contar con el brazalete de acceso al servicio de alimentos y bebidas. Debe portarse en la muñeca sin excepción."], "inscripcionesText": "Inscripciones: https://terralta.speitour.com (información del torneo, salidas, programa de juego y resultados).\\nInicio Socios: 16 de abril de 2026. Inicio Invitados: 1 de mayo de 2026. Cierre: 22 de junio de 2026."}',
  enabled = 1,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO convocatoria_content (torneoid, section_id, section_type, content, enabled) VALUES (349, 'costos', 'generic', '{"sociosPricing": [{"title": "Costo de Inscripción — Socios", "subtitle": "Cuotas aplicables únicamente para jugadores que participen en el Torneo.", "tiers": [{"categoria": "Caballeros Hijos", "costo": "$11,200.00"}, {"categoria": "Damas Hijas", "costo": "$5,800.00"}, {"categoria": "Socios Menores de 18 años", "costo": "$4,000.00"}]}], "foraneosPricing": [{"title": "Costo de Inscripción — Invitados", "subtitle": "Pago en una sola exhibición.", "tiers": [{"categoria": "Caballeros Invitados (incluye cónyuge en centros de consumo)", "costo": "$17,500.00"}, {"categoria": "Damas Invitadas (cónyuge no jugador con acceso a centros de consumo)", "costo": "$9,000.00"}, {"categoria": "Damas Invitadas (cónyuge juega el Torneo) — 50% aplicado", "costo": "$4,500.00"}, {"categoria": "Invitados Menores de 18 años", "costo": "$6,000.00"}, {"categoria": "Invitados Centros de Consumo (no jugadores) — por día", "costo": "$2,000.00"}, {"categoria": "Invitados Centros de Consumo (no jugadores) — toda la semana", "costo": "$8,000.00"}]}], "pricingNote": "Cargos de inscripción para Socios: si se inscriben en abril, el cargo se distribuye en 3 meses (abril, mayo y junio); en mayo, en 2 meses (mayo y junio); en junio, en 1 solo mes. Cónyuge jugadora aplica un 50% en su inscripción (Damas Invitadas) siempre y cuando ambos jueguen el torneo. Cancelaciones: no se aceptan bonificaciones por cancelación posterior al 25 de mayo; la cancelación deberá ser por https://terralta.speitour.com, sin excepción. La inscripción no es transferible.", "contactInfo": {"bankName": "Bancrea", "clabe": "152580120000725303", "cuenta": "12000072530", "nombre": "Terralta A.C.", "email": "", "telefono": "", "telefonoDirecto": ""}, "contactWarning": "Inscripciones e información completa en https://terralta.speitour.com", "inscripcionesText": "Inicio Socios: 16 de abril de 2026. Inicio Invitados: 1 de mayo de 2026. Cierre de inscripciones: 22 de junio de 2026."}', 1)
ON DUPLICATE KEY UPDATE
  section_type = 'generic',
  content = '{"sociosPricing": [{"title": "Costo de Inscripción — Socios", "subtitle": "Cuotas aplicables únicamente para jugadores que participen en el Torneo.", "tiers": [{"categoria": "Caballeros Hijos", "costo": "$11,200.00"}, {"categoria": "Damas Hijas", "costo": "$5,800.00"}, {"categoria": "Socios Menores de 18 años", "costo": "$4,000.00"}]}], "foraneosPricing": [{"title": "Costo de Inscripción — Invitados", "subtitle": "Pago en una sola exhibición.", "tiers": [{"categoria": "Caballeros Invitados (incluye cónyuge en centros de consumo)", "costo": "$17,500.00"}, {"categoria": "Damas Invitadas (cónyuge no jugador con acceso a centros de consumo)", "costo": "$9,000.00"}, {"categoria": "Damas Invitadas (cónyuge juega el Torneo) — 50% aplicado", "costo": "$4,500.00"}, {"categoria": "Invitados Menores de 18 años", "costo": "$6,000.00"}, {"categoria": "Invitados Centros de Consumo (no jugadores) — por día", "costo": "$2,000.00"}, {"categoria": "Invitados Centros de Consumo (no jugadores) — toda la semana", "costo": "$8,000.00"}]}], "pricingNote": "Cargos de inscripción para Socios: si se inscriben en abril, el cargo se distribuye en 3 meses (abril, mayo y junio); en mayo, en 2 meses (mayo y junio); en junio, en 1 solo mes. Cónyuge jugadora aplica un 50% en su inscripción (Damas Invitadas) siempre y cuando ambos jueguen el torneo. Cancelaciones: no se aceptan bonificaciones por cancelación posterior al 25 de mayo; la cancelación deberá ser por https://terralta.speitour.com, sin excepción. La inscripción no es transferible.", "contactInfo": {"bankName": "Bancrea", "clabe": "152580120000725303", "cuenta": "12000072530", "nombre": "Terralta A.C.", "email": "", "telefono": "", "telefonoDirecto": ""}, "contactWarning": "Inscripciones e información completa en https://terralta.speitour.com", "inscripcionesText": "Inicio Socios: 16 de abril de 2026. Inicio Invitados: 1 de mayo de 2026. Cierre de inscripciones: 22 de junio de 2026."}',
  enabled = 1,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO convocatoria_content (torneoid, section_id, section_type, content, enabled) VALUES (349, 'premiacion', 'list', '{"items": [{"categoria": "Caballeros", "premios": ["1er, 2do y 3er lugar por categoría (Campeonato, Premier, AA, A, B, C, D, Seniors y Super Seniors)."]}, {"categoria": "Damas — 1ª Categoría", "premios": ["1er lugar Gross", "1er, 2do y 3er lugar Neto"]}, {"categoria": "Damas — 2ª, 3ª, 4ª y Estrellal", "premios": ["1er, 2do y 3er lugar Neto por categoría."]}, {"categoria": "Hole In One", "premios": ["$1,000,000 al primer Hole In One en cualquier par 3 (hoyos 3, 5, 7, 12 y 16).", "Premios adicionales por hoyo para el primer Hole In One en cada par 3."]}, {"categoria": "Mejor O´yes general del Torneo", "premios": ["Premio especial al mejor O´yes general del Torneo (no aplica Hole In One)."]}]}', 1)
ON DUPLICATE KEY UPDATE
  section_type = 'list',
  content = '{"items": [{"categoria": "Caballeros", "premios": ["1er, 2do y 3er lugar por categoría (Campeonato, Premier, AA, A, B, C, D, Seniors y Super Seniors)."]}, {"categoria": "Damas — 1ª Categoría", "premios": ["1er lugar Gross", "1er, 2do y 3er lugar Neto"]}, {"categoria": "Damas — 2ª, 3ª, 4ª y Estrellal", "premios": ["1er, 2do y 3er lugar Neto por categoría."]}, {"categoria": "Hole In One", "premios": ["$1,000,000 al primer Hole In One en cualquier par 3 (hoyos 3, 5, 7, 12 y 16).", "Premios adicionales por hoyo para el primer Hole In One en cada par 3."]}, {"categoria": "Mejor O´yes general del Torneo", "premios": ["Premio especial al mejor O´yes general del Torneo (no aplica Hole In One)."]}]}',
  enabled = 1,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO convocatoria_content (torneoid, section_id, section_type, content, enabled) VALUES (349, 'competencias', 'list', '{"items": [{"nombre": "Torneo de Driver de Distancia Caballeros", "descripcion": "Sistema: solo el primer golpe del Hoyo 1. Días: viernes 26 de junio al viernes 3 de julio (durante la ronda de juego). Categorías: Seniors, D, C, B, A y AA.", "premios": "Technogym Connected Dumbbells."}, {"nombre": "Torneo de Driver de Precisión Damas", "descripcion": "Sistema: solo el primer golpe del Hoyo 10 en los tres días de la competencia. Días: viernes 26, lunes 29 de junio y miércoles 1 de julio (durante la ronda de juego).", "premios": "1° $10,000 · 2° $6,000 · 3° $4,000 (Certificados Back 9)."}, {"nombre": "Torneo de Long Driver Caballeros", "descripcion": "Día: jueves 2 de julio, 17:00 a 19:30 hrs. Lugar: Terraza Bar ''La Vista''. Registro: mesa diaria de 14:00 a 18:00 hrs (no se puede participar dos veces ni repetir otro día). Calificarán a la final los mejores 52 lugares (42 caballeros y 10 damas) de los 7 días. Final: viernes 3 de julio, 20:30 hrs en Terraza Bar ''La Vista''. Cada participante tendrá 3 tiros y contará el tiro más cercano. El primer Hole In One será el mejor tiro. Empates: tiro adicional, gana quien la deje más cerca.", "premios": "1° $10,000 · 2° $6,000 · 3° $4,000 (Certificados Back 9)."}, {"nombre": "Torneo de Approach Mixto", "descripcion": "Calificación: viernes 26 de junio al jueves 2 de julio, 14:00 a 18:00 hrs en el Tee de Práctica. Cada jugador tendrá 3 oportunidades; califican los 7 mejores tiros del día. En total, calificarán 42 caballeros y 10 damas. Final: viernes 3 de julio, 20:30 hrs en Terraza Bar ''La Vista''. En caso de empates, gana el jugador que haya hecho el tiro primero.", "premios": "CFMoto CFORCE C5 al ganador del Torneo de Approach Mixto. 1° $10,000 · 2° $6,000 · 3° $4,000 (Certificados Back 9)."}, {"nombre": "Torneo de Putt Caballeros", "descripcion": "Calificación: viernes 26, sábado 27, domingo 28 de junio y jueves 2 de julio, 14:00 a 18:00 hrs en el Putting Green. Final: viernes 3 de julio, 18:00 hrs en el Putting Green.", "premios": "1° $10,000 · 2° $6,000 · 3° $4,000 (Certificados Back 9)."}, {"nombre": "Torneo de Putt Damas", "descripcion": "Día: lunes 29 de junio, 16:00 hrs en el Putting Green.", "premios": "1° $10,000 · 2° $6,000 · 3° $4,000 (Certificados Back 9)."}, {"nombre": "Premios de O´yes", "descripcion": "Se premiarán los mejores O´yes diarios del Torneo en los hoyos 3, 5, 7, 12 y 16. También se premiará al mejor O´yes general de cada par 3 de todo el torneo. En caso de empate, gana quien hizo el tiro primero. Un jugador puede ganar dos o más O´yes con tiros diferentes.", "premios": "Premios por hoyo + premio especial al mejor O´yes general del Torneo (no aplica Hole In One)."}]}', 1)
ON DUPLICATE KEY UPDATE
  section_type = 'list',
  content = '{"items": [{"nombre": "Torneo de Driver de Distancia Caballeros", "descripcion": "Sistema: solo el primer golpe del Hoyo 1. Días: viernes 26 de junio al viernes 3 de julio (durante la ronda de juego). Categorías: Seniors, D, C, B, A y AA.", "premios": "Technogym Connected Dumbbells."}, {"nombre": "Torneo de Driver de Precisión Damas", "descripcion": "Sistema: solo el primer golpe del Hoyo 10 en los tres días de la competencia. Días: viernes 26, lunes 29 de junio y miércoles 1 de julio (durante la ronda de juego).", "premios": "1° $10,000 · 2° $6,000 · 3° $4,000 (Certificados Back 9)."}, {"nombre": "Torneo de Long Driver Caballeros", "descripcion": "Día: jueves 2 de julio, 17:00 a 19:30 hrs. Lugar: Terraza Bar ''La Vista''. Registro: mesa diaria de 14:00 a 18:00 hrs (no se puede participar dos veces ni repetir otro día). Calificarán a la final los mejores 52 lugares (42 caballeros y 10 damas) de los 7 días. Final: viernes 3 de julio, 20:30 hrs en Terraza Bar ''La Vista''. Cada participante tendrá 3 tiros y contará el tiro más cercano. El primer Hole In One será el mejor tiro. Empates: tiro adicional, gana quien la deje más cerca.", "premios": "1° $10,000 · 2° $6,000 · 3° $4,000 (Certificados Back 9)."}, {"nombre": "Torneo de Approach Mixto", "descripcion": "Calificación: viernes 26 de junio al jueves 2 de julio, 14:00 a 18:00 hrs en el Tee de Práctica. Cada jugador tendrá 3 oportunidades; califican los 7 mejores tiros del día. En total, calificarán 42 caballeros y 10 damas. Final: viernes 3 de julio, 20:30 hrs en Terraza Bar ''La Vista''. En caso de empates, gana el jugador que haya hecho el tiro primero.", "premios": "CFMoto CFORCE C5 al ganador del Torneo de Approach Mixto. 1° $10,000 · 2° $6,000 · 3° $4,000 (Certificados Back 9)."}, {"nombre": "Torneo de Putt Caballeros", "descripcion": "Calificación: viernes 26, sábado 27, domingo 28 de junio y jueves 2 de julio, 14:00 a 18:00 hrs en el Putting Green. Final: viernes 3 de julio, 18:00 hrs en el Putting Green.", "premios": "1° $10,000 · 2° $6,000 · 3° $4,000 (Certificados Back 9)."}, {"nombre": "Torneo de Putt Damas", "descripcion": "Día: lunes 29 de junio, 16:00 hrs en el Putting Green.", "premios": "1° $10,000 · 2° $6,000 · 3° $4,000 (Certificados Back 9)."}, {"nombre": "Premios de O´yes", "descripcion": "Se premiarán los mejores O´yes diarios del Torneo en los hoyos 3, 5, 7, 12 y 16. También se premiará al mejor O´yes general de cada par 3 de todo el torneo. En caso de empate, gana quien hizo el tiro primero. Un jugador puede ganar dos o más O´yes con tiros diferentes.", "premios": "Premios por hoyo + premio especial al mejor O´yes general del Torneo (no aplica Hole In One)."}]}',
  enabled = 1,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO convocatoria_content (torneoid, section_id, section_type, content, enabled) VALUES (349, 'servicios', 'list', '{"items": [{"nombre": "Música en vivo — ''Los Olivos''", "descripcion": "Del 26 de junio al 4 de julio, 2 P.M. a 4 P.M."}, {"nombre": "DJ — ''Hoyo 19''", "descripcion": "Del 26 de junio al 4 de julio, 8 P.M. a 10 P.M."}, {"nombre": "Cata de Vinos", "descripcion": "Miércoles 1 de julio, 7:00 P.M. a 9:00 P.M. en Plaza ''Los Olivos'' (música en vivo)."}, {"nombre": "Bingo — Tarde de Damas", "descripcion": "Consultar agenda. Reservaciones e informes al 81 8093 1078."}, {"nombre": "Noche de Casino", "descripcion": "Julio 2, 19:00 a 23:00 hrs en Hoyo 19. Reservaciones al 81 8093 1078."}, {"nombre": "Ceremonia de Premiación", "descripcion": "Julio 4, 4:00 P.M. en Hoyo 19."}]}', 1)
ON DUPLICATE KEY UPDATE
  section_type = 'list',
  content = '{"items": [{"nombre": "Música en vivo — ''Los Olivos''", "descripcion": "Del 26 de junio al 4 de julio, 2 P.M. a 4 P.M."}, {"nombre": "DJ — ''Hoyo 19''", "descripcion": "Del 26 de junio al 4 de julio, 8 P.M. a 10 P.M."}, {"nombre": "Cata de Vinos", "descripcion": "Miércoles 1 de julio, 7:00 P.M. a 9:00 P.M. en Plaza ''Los Olivos'' (música en vivo)."}, {"nombre": "Bingo — Tarde de Damas", "descripcion": "Consultar agenda. Reservaciones e informes al 81 8093 1078."}, {"nombre": "Noche de Casino", "descripcion": "Julio 2, 19:00 a 23:00 hrs en Hoyo 19. Reservaciones al 81 8093 1078."}, {"nombre": "Ceremonia de Premiación", "descripcion": "Julio 4, 4:00 P.M. en Hoyo 19."}]}',
  enabled = 1,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO convocatoria_content (torneoid, section_id, section_type, content, enabled) VALUES (349, 'desempates', 'generic', '{}', 0)
ON DUPLICATE KEY UPDATE
  section_type = 'generic',
  content = '{}',
  enabled = 0,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO convocatoria_content (torneoid, section_id, section_type, content, enabled) VALUES (349, 'reglas', 'generic', '{"items": []}', 0)
ON DUPLICATE KEY UPDATE
  section_type = 'generic',
  content = '{"items": []}',
  enabled = 0,
  updated_at = CURRENT_TIMESTAMP;

COMMIT;
