-- =====================================================================
-- Fix: /convocatoria costos for torneoid=349 (Terralta)
-- Reubica invitados dentro de sociosPricing (tabla), ya que foraneosPricing
-- solo soporta {caballeros, damasSeniors} y no rinde 6 tipos de invitados.
-- =====================================================================

START TRANSACTION;

INSERT INTO convocatoria_content (torneoid, section_id, section_type, content, enabled) VALUES (349, 'costos', 'generic', '{"sociosPricing": [{"title": "Costo de Inscripción — Socios", "subtitle": "Cuotas aplicables únicamente para jugadores que participen en el Torneo.", "tiers": [{"categoria": "Caballeros Hijos", "costo": "$11,200.00"}, {"categoria": "Damas Hijas", "costo": "$5,800.00"}, {"categoria": "Socios Menores de 18 años", "costo": "$4,000.00"}]}, {"title": "Costo de Inscripción — Invitados", "subtitle": "Pago en una sola exhibición.", "tiers": [{"categoria": "Caballeros Invitados (incluye cónyuge en centros de consumo)", "costo": "$17,500.00"}, {"categoria": "Damas Invitadas (cónyuge no jugador con acceso a centros de consumo)", "costo": "$9,000.00"}, {"categoria": "Damas Invitadas (cónyuge juega el Torneo) — 50% aplicado", "costo": "$4,500.00"}, {"categoria": "Invitados Menores de 18 años", "costo": "$6,000.00"}, {"categoria": "Invitados Centros de Consumo (no jugadores) — por día", "costo": "$2,000.00"}, {"categoria": "Invitados Centros de Consumo (no jugadores) — toda la semana", "costo": "$8,000.00"}]}], "foraneosPricing": [], "pricingNote": "Cargos de inscripción para Socios: si se inscriben en abril, el cargo se distribuye en 3 meses (abril, mayo y junio); en mayo, en 2 meses (mayo y junio); en junio, en 1 solo mes. Cónyuge jugadora aplica un 50% en su inscripción (Damas Invitadas) siempre y cuando ambos jueguen el torneo. Cancelaciones: no se aceptan bonificaciones por cancelación posterior al 25 de mayo; la cancelación deberá ser por https://terralta.speitour.com, sin excepción. La inscripción no es transferible.", "contactInfo": {"bankName": "Bancrea", "clabe": "152580120000725303", "cuenta": "12000072530", "nombre": "Terralta A.C.", "email": "", "telefono": "", "telefonoDirecto": ""}, "contactWarning": "Inscripciones e información completa en https://terralta.speitour.com", "inscripcionesText": "Inicio Socios: 16 de abril de 2026. Inicio Invitados: 1 de mayo de 2026. Cierre de inscripciones: 22 de junio de 2026."}', 1)
ON DUPLICATE KEY UPDATE
  section_type = 'generic',
  content = '{"sociosPricing": [{"title": "Costo de Inscripción — Socios", "subtitle": "Cuotas aplicables únicamente para jugadores que participen en el Torneo.", "tiers": [{"categoria": "Caballeros Hijos", "costo": "$11,200.00"}, {"categoria": "Damas Hijas", "costo": "$5,800.00"}, {"categoria": "Socios Menores de 18 años", "costo": "$4,000.00"}]}, {"title": "Costo de Inscripción — Invitados", "subtitle": "Pago en una sola exhibición.", "tiers": [{"categoria": "Caballeros Invitados (incluye cónyuge en centros de consumo)", "costo": "$17,500.00"}, {"categoria": "Damas Invitadas (cónyuge no jugador con acceso a centros de consumo)", "costo": "$9,000.00"}, {"categoria": "Damas Invitadas (cónyuge juega el Torneo) — 50% aplicado", "costo": "$4,500.00"}, {"categoria": "Invitados Menores de 18 años", "costo": "$6,000.00"}, {"categoria": "Invitados Centros de Consumo (no jugadores) — por día", "costo": "$2,000.00"}, {"categoria": "Invitados Centros de Consumo (no jugadores) — toda la semana", "costo": "$8,000.00"}]}], "foraneosPricing": [], "pricingNote": "Cargos de inscripción para Socios: si se inscriben en abril, el cargo se distribuye en 3 meses (abril, mayo y junio); en mayo, en 2 meses (mayo y junio); en junio, en 1 solo mes. Cónyuge jugadora aplica un 50% en su inscripción (Damas Invitadas) siempre y cuando ambos jueguen el torneo. Cancelaciones: no se aceptan bonificaciones por cancelación posterior al 25 de mayo; la cancelación deberá ser por https://terralta.speitour.com, sin excepción. La inscripción no es transferible.", "contactInfo": {"bankName": "Bancrea", "clabe": "152580120000725303", "cuenta": "12000072530", "nombre": "Terralta A.C.", "email": "", "telefono": "", "telefonoDirecto": ""}, "contactWarning": "Inscripciones e información completa en https://terralta.speitour.com", "inscripcionesText": "Inicio Socios: 16 de abril de 2026. Inicio Invitados: 1 de mayo de 2026. Cierre de inscripciones: 22 de junio de 2026."}',
  enabled = 1,
  updated_at = CURRENT_TIMESTAMP;

COMMIT;
